"""Initial migration

Revision ID: 966b4e347c0e
Revises: 
Create Date: 2025-12-01 21:20:27.700355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '966b4e347c0e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countermeasures',
    sa.Column('measure_id', sa.Integer(), nullable=False),
    sa.Column('measure_name', sa.String(length=255), nullable=False),
    sa.Column('measure_type', sa.String(length=100), nullable=True),
    sa.Column('implementation_cost', sa.Float(), nullable=True),
    sa.Column('effectiveness_level', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('measure_id')
    )
    op.create_table('criteria',
    sa.Column('criteria_id', sa.Integer(), nullable=False),
    sa.Column('criteria_name', sa.String(length=255), nullable=False),
    sa.Column('criteria_category', sa.String(length=100), nullable=True),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('criteria_id')
    )
    op.create_table('objects',
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('object_name', sa.String(length=255), nullable=False),
    sa.Column('object_type', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('owner_organization', sa.String(length=255), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('object_id')
    )
    op.create_table('threats',
    sa.Column('threat_id', sa.Integer(), nullable=False),
    sa.Column('threat_name', sa.String(length=255), nullable=False),
    sa.Column('threat_description', sa.Text(), nullable=True),
    sa.Column('threat_probability', sa.Float(), nullable=True),
    sa.Column('threat_impact', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('threat_id')
    )
    op.create_table('vulnerabilities',
    sa.Column('vulnerability_id', sa.Integer(), nullable=False),
    sa.Column('vulnerability_name', sa.String(length=255), nullable=False),
    sa.Column('vulnerability_description', sa.Text(), nullable=True),
    sa.Column('affected_component', sa.String(length=255), nullable=True),
    sa.Column('severity_level', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('vulnerability_id')
    )
    op.create_table('assessments',
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('assessment_date', sa.DateTime(), nullable=True),
    sa.Column('assessor_id', sa.Integer(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['object_id'], ['objects.object_id'], ),
    sa.PrimaryKeyConstraint('assessment_id')
    )
    op.create_table('assessment_scores',
    sa.Column('score_id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('criteria_id', sa.Integer(), nullable=False),
    sa.Column('score_value', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.assessment_id'], ),
    sa.ForeignKeyConstraint(['criteria_id'], ['criteria.criteria_id'], ),
    sa.PrimaryKeyConstraint('score_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assessment_scores')
    op.drop_table('assessments')
    op.drop_table('vulnerabilities')
    op.drop_table('threats')
    op.drop_table('objects')
    op.drop_table('criteria')
    op.drop_table('countermeasures')
    # ### end Alembic commands ###
